<!DOCTYPE html>
<html lang="uk">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Адмін панель - Віршована</title>
    <?= $this->render('../page/style') ?>
</head>

<body>
    <div class="admin-container">
        <main class="admin-main">
            <?= $this->render($this->getTemplate()) ?>
        </main>
    </div>
</body>

</html>