<?php
foreach ($this('collection') as $poem): ?>
    <article class="poem-vintage">
        <div class="poem-sheet">
            <div class="poem-header">
                <div class="poem-header">
                    <h2 class="poem-title-vintage"><?= htmlspecialchars($poem('title')) ?></h2>
                </div>
                <div class="poem-body-vintage"><?= htmlspecialchars($poem('virsh')) ?></div>
                <?php if ($poem('illustration')): ?>
                <div class="poem-body-illustration">
                    <img src="/<?= htmlspecialchars($poem('illustration')) ?>" alt="Ілюстрація до вірша">
                </div>
                <?php endif; ?>
                <?php if ($poem('youtube')): ?>
                <div class="poem-body-youtube">
                    <iframe src="<?= htmlspecialchars($poem('youtube')) ?>" allowfullscreen></iframe>
                </div>
                <?php endif; ?>
                <div class="poem-footer">Кінець</div>
            </div>
    </article>
<?php endforeach ?>